// @meals/core - Domain logic and repositories
export const version = '0.1.0';

// Database connection
export { getDb, closeDb, isDbOpen } from './db/connection.js';
export type { Database, DbOptions } from './db/connection.js';

// Database migrations
export {
  migrate,
  getAppliedMigrations,
  getDefaultMigrationsDir,
} from './db/migrate.js';

// Models - Zod schemas and TypeScript types
export {
  // Ingredient
  IngredientSchema,
  CreateIngredientSchema,
  UpdateIngredientSchema,
  StoreSectionEnum,
  STORE_SECTIONS,
  isValidStoreSection,
  type Ingredient,
  type CreateIngredient,
  type UpdateIngredient,
  type StoreSection,
  // Tag
  TagCategoryEnum,
  TagSchema,
  CreateTagSchema,
  UpdateTagSchema,
  RecipeTagSchema,
  type TagCategory,
  type Tag,
  type CreateTag,
  type UpdateTag,
  type RecipeTag,
  // Recipe
  SourceTypeEnum,
  DifficultyEnum,
  RecipeIngredientSchema,
  CreateRecipeIngredientSchema,
  RecipeSchema,
  CreateRecipeSchema,
  UpdateRecipeSchema,
  RecipeWithRelationsSchema,
  type SourceType,
  type Difficulty,
  type RecipeIngredient,
  type CreateRecipeIngredient,
  type Recipe,
  type CreateRecipe,
  type UpdateRecipe,
  type RecipeWithRelations,
  // Plan
  ISO_WEEK_REGEX,
  IsoWeekSchema,
  isValidIsoWeek,
  PlanStatusEnum,
  MealTypeEnum,
  SlotTypeEnum,
  DayOfWeekSchema,
  WeeklyPlanSchema,
  CreateWeeklyPlanSchema,
  UpdateWeeklyPlanSchema,
  PlanItemSchema,
  CreatePlanItemSchema,
  UpdatePlanItemSchema,
  WeeklyPlanWithItemsSchema,
  type IsoWeek,
  type PlanStatus,
  type MealType,
  type SlotType,
  type DayOfWeek,
  type WeeklyPlan,
  type CreateWeeklyPlan,
  type UpdateWeeklyPlan,
  type PlanItem,
  type CreatePlanItem,
  type UpdatePlanItem,
  type WeeklyPlanWithItems,
  // Preference
  PlanningHeuristicsSchema,
  UserPreferencesSchema,
  PreferenceKeyEnum,
  DEFAULT_PREFERENCES,
  PreferenceRowSchema,
  SetPreferenceSchema,
  PreferenceValueSchemas,
  getDefaultPreference,
  validatePreferenceValue,
  parsePreferenceValue,
  // Enhanced preference exports (T044)
  AllergySeverityEnum,
  AllergyEntrySchema,
  CuisinePreferencesSchema,
  PrepDayEnum,
  type PlanningHeuristics,
  type UserPreferences,
  type PreferenceKey,
  type PreferenceRow,
  type SetPreference,
  // Enhanced preference types (T044)
  type AllergySeverity,
  type AllergyEntry,
  type CuisinePreferences,
  type PrepDay,
  // Pantry models (T031)
  PantryLocationEnum,
  PantryItemSchema,
  PantryItemWithIngredientSchema,
  CreatePantryItemSchema,
  UpdatePantryItemSchema,
  PANTRY_LOCATIONS,
  isValidPantryLocation,
  type PantryLocation,
  type PantryItem,
  type PantryItemWithIngredient,
  type CreatePantryItem,
  type UpdatePantryItem,
  // Prep batch models (T041)
  PrepBatchSchema,
  CreatePrepBatchSchema,
  UpdatePrepBatchSchema,
  PrepBatchWithRecipeSchema,
  PrepBatchWithRemainingSchema,
  type PrepBatch,
  type CreatePrepBatch,
  type UpdatePrepBatch,
  type PrepBatchWithRecipe,
  type PrepBatchWithRemaining,
  // Substitution models (T046)
  SubstitutionSchema,
  CreateSubstitutionSchema,
  UpdateSubstitutionSchema,
  DIETARY_TAGS,
  isValidDietaryTag,
  type Substitution,
  type CreateSubstitution,
  type UpdateSubstitution,
  type DietaryTag,
} from './models/index.js';

// Repositories
export {
  RecipeRepository,
  type CreateRecipeIngredientInput,
  type ListRecipesOptions,
  AuditRepository,
  type AuditActor,
  type AuditAction,
  type CreateAuditLogEntry,
  type AuditLogEntry,
  PlanRepository,
  type ListPlansOptions,
  PreferenceRepository,
  type PreferenceData,
  TagRepository,
  IngredientRepository,
  INGREDIENT_CATEGORIES,
  getAutoCategory,
  getAutoStoreSection,
  isValidCategory,
  type IngredientCategory,
  GroceryListRepository,
  type PersistedGroceryList,
  type PersistedGroceryItem,
  type PersistedGroceryListWithItems,
  type CreateGroceryItemInput,
  type UpdateGroceryItemInput,
  // Pantry repository (T031)
  PantryRepository,
  type ListPantryItemsOptions,
  // Recipe modification repository (T047)
  RecipeModificationRepository,
  type RecipeModification,
  type IngredientOverride,
  type UpsertRecipeModification,
  // Prep batch repository (T041)
  PrepBatchRepository,
  type ListPrepBatchesOptions,
  // Substitution repository (T046)
  SubstitutionRepository,
  type ListSubstitutionsOptions,
} from './repos/index.js';

// Re-export GroceryItemStatus type from repos
export type { GroceryItemStatus } from './repos/index.js';

// Services
export {
  RecipeService,
  PlanService,
  GroceryService,
  type GroceryItem,
  type GroceryGroup,
  type GroceryList,
  type GroceryListItemWithStatus,
  type PersistentGroceryList,
  type CheckPantryResult,
  type GenerateListOptions,
  // Pantry service (T031)
  PantryService,
  type AddPantryItemInput,
  type AddPantryItemResult,
  PreferenceService,
  ImportService,
  type ImportedRecipeData,
  type ImportResult,
  type SaveImportResult,
  type ImportOptions,
  SuggestionService,
  type SuggestionReason,
  type RecipeSuggestion,
  type SuggestionContext,
  type GetSuggestionsOptions,
  SCORING_WEIGHTS,
  RECENT_DAYS_THRESHOLD,
  // Prep batch service (T041)
  PrepBatchService,
  // Substitution service (T046)
  SubstitutionService,
  type SubstitutionSuggestion,
  type GetSubstitutionSuggestionsOptions,
  // RecipeService substitution-related types (T046)
  type IngredientWithSubstitutions,
  type RecipeSubstitutionSuggestions,
  // Prep day service (T051)
  PrepDayService,
  type PrepTaskItem,
  type PrepTask,
  type PrepDayBatch,
  type RecipeSummary,
  type PrepDaySummary,
} from './services/index.js';
